#!/bin/bash
#
# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ "$#" -gt "0" ]; then
    RELEASE=$1
    shift
else
    RELEASE=$(uname -r)
fi

DIRNAME=$(dirname $0)
URL=$(PATH=$PATH:/sbin:/usr/sbin fakeroot $DIRNAME/novm mkkernel --release=$RELEASE "$@")
$DIRNAME/novm getkernel --url $URL
