#!/usr/bin/env python
#
# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
novm management script.
"""

import os
import sys

if os.path.exists(os.path.join("novm", "__init__.py")):
    sys.path.insert(0, ".")

lib_path = os.path.join(
    os.path.abspath(os.path.dirname(__file__)),
    "..", "lib", "novm", "python")
sys.path.append(lib_path)

import novm.cli

if __name__ == "__main__":
    novm.cli.main(sys.argv[1:])
