#!/bin/bash

set -e

if [ "$#" -gt "0" ]; then
    RELEASE=$1
    shift
else
    RELEASE=$(uname -r)
fi

DIRNAME=$(dirname $0)
URL=$(PATH=$PATH:/sbin:/usr/sbin fakeroot $DIRNAME/novm mkkernel --release=$RELEASE "$@")
$DIRNAME/novm getkernel --url $URL
