#!/bin/sh

# Parse our command line arguments.
# Critically this will include information
# about attached devices, IP addresses, etc.
for x in $(cat /proc/cmdline); do
    case $x in
    init=*)
        init=${x#init=}
        ;;
    esac
done

# Try logging.
echo "Initial ramdisk running..." > /dev/kmsg

# Load all virt-io modules.
modprobe virtio-pci
modprobe virtio-net
modprobe virtio-block
modprobe virtio-console
modprobe 9pnet_virtio
modprobe 9p

# Execute our noinit process.
#
# The first thing this will do is
# call pivot_root given the argument.
#
# The second thing it will do is open
# the virtIO console and become an RPC
# server for the backend. Yeehaw!
exec /sysroot/noguest -pivot_root /root
