#!/bin/bash

set -e

if [ "$#" -ne "2" ]; then
    echo "usage: $0 <kernel-version> <module-path>"
    exit 1
fi

KERNEL_VERSION=$1
MOD_PATH=$2

# Create a temporary directories.
# These will be cleaned up automatically.
unsorted=$(mktemp /tmp/unsorted.XXXXXXXXXX)
WDIR=$(mktemp -d /tmp/initrd-work.XXXXXXXXXX)

cleanup() {
    rm -rf $unsorted
    rm -rf $WDIR
}
trap cleanup EXIT

# Create base directory structure.
mkdir -p $WDIR/{bin,dev,lib/firmware,run,sbin,sys,proc}
mkdir -p $WDIR/etc/{modprobe.d,udev/rules.d}
touch $WDIR/etc/modprobe.d/modprobe.conf
ln -s lib $WDIR/lib64

# Create necessary device nodes.
mknod -m 640 $WDIR/dev/console c 5 1
mknod -m 664 $WDIR/dev/null    c 1 3

# Install the init file.
install -m0755 $(dirname $0)/init $WDIR/init

# Copy our files.
binfiles="sh sleep mount umount mkdir ln"
sbinfiles="modprobe switch_root"

if [ -x /bin/kmod ] ; then
    binfiles="$binfiles kmod"
else
    binfiles="$binfiles lsmod"
    sbinfiles="$sbinfiles insmod"
fi

copy()
{
    local file

    if [ "$2" = "lib" ]; then
        if [ -r $1 ]; then
            file=$1
        else
            # File the library on our standard path.
            file=$(find /lib /lib64 /usr/lib /usr/lib64 -name $1 2>/dev/null | head -n 1)
        fi
    else
        file=/$2/$1
    fi

    if ! cp $file $WDIR/$2; then
        echo "Missing required file: $file for directory $2"
        return 1
    fi
}

for f in $binfiles; do
    ldd /bin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
    copy $f bin
done
for f in $sbinfiles; do
    ldd /sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
    copy $f sbin
done

sort $unsorted | uniq | while read library ; do
    if [ "$library" == "linux-vdso.so.1" ] ||
       [ "$library" == "linux-gate.so.1" ]; then
        continue
    fi
    copy $library lib
done

# Install all virtio modules.
# For user convenience, we also include all filesystems,
# and all crypto modules. They could certainly built this
# into their image and load it separately, but why not.

find $MOD_PATH \
    -name virtio_\*.ko \
    -o -name 9p.ko \
    -o -name 9pnet.ko \
    -o -name 9pnet_virtio.ko \
    | cpio --make-directories -p --quiet $WDIR

cp $MOD_PATH/modules.{builtin,order} \
  $WDIR/lib/modules/$KERNEL_VERSION

depmod -b $WDIR $KERNEL_VERSION

# Create our initrd.
(cd $WDIR; find . | cpio -o -H newc --quiet | gzip -9)
